
spring:
  main: 
    allow-bean-definition-overriding: true

dubbo:
  application:
    name: service-app1
  registry:
    address: zookeeper://192.168.56.101:2181
  protocol:
    #name: memcached
    #name: http
    #server: tomcat
    #server: servlet
    #name: hessian
    #server: tomcat
    #name: rmi
    name: hessian
    #port: 8080
    server: tomcat
    port: 20880
#  scan:
#    base-packages: com.study.mike.dubbo.provider
